// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDiv7-b6tHtakkTsoowlE854IapXzdjE',
    appId: '1:514659484039:web:363f267f093c87323c1322',
    messagingSenderId: '514659484039',
    projectId: 'true-balance-8dac7',
    authDomain: 'true-balance-8dac7.firebaseapp.com',
    storageBucket: 'true-balance-8dac7.firebasestorage.app',
    measurementId: 'G-0Q09Q5PLYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8d0d8qcaYU_ueA3dXAmAQ6EWGx5bdC3Y',
    appId: '1:514659484039:android:ee093eab72f01f9d3c1322',
    messagingSenderId: '514659484039',
    projectId: 'true-balance-8dac7',
    storageBucket: 'true-balance-8dac7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh0mFcWEcn8Tz_GAwpRGLBNH5scZE18sI',
    appId: '1:514659484039:ios:4d4b18cdb4aab9bb3c1322',
    messagingSenderId: '514659484039',
    projectId: 'true-balance-8dac7',
    storageBucket: 'true-balance-8dac7.firebasestorage.app',
    iosBundleId: 'com.example.truebalanceclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh0mFcWEcn8Tz_GAwpRGLBNH5scZE18sI',
    appId: '1:514659484039:ios:4d4b18cdb4aab9bb3c1322',
    messagingSenderId: '514659484039',
    projectId: 'true-balance-8dac7',
    storageBucket: 'true-balance-8dac7.firebasestorage.app',
    iosBundleId: 'com.example.truebalanceclient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDiv7-b6tHtakkTsoowlE854IapXzdjE',
    appId: '1:514659484039:web:80cb2cf179d9a3b93c1322',
    messagingSenderId: '514659484039',
    projectId: 'true-balance-8dac7',
    authDomain: 'true-balance-8dac7.firebaseapp.com',
    storageBucket: 'true-balance-8dac7.firebasestorage.app',
    measurementId: 'G-2FX964KSLL',
  );
}
